// Clase 25 - Try Catch
// La caracter√≠stica agregada es que en el catch se le puede
// pasar un error personalizado

try {
    funcion1();
} catch (error) {
    console.log(error);
}

// Sin el error del catch
try {
    funcion2();
} catch {
    console.log("Error!!!"); 
}